apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ansible-app
  labels:
    app: k8s-ansible-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-ansible-app
  template:
    metadata:
      labels:
        app: k8s-ansible-app
    spec:
      containers:
        - name: k8s-ansible-app
          image: subash309206/k8s-ansible-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
