apiVersion: v1
kind: Service
metadata:
  name: k8s-ansible-app-service
spec:
  type: NodePort
  selector:
    app: k8s-ansible-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
